# Generated by Django 4.2 on 2023-05-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_customuser_options_alter_customuser_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "MALE"), ("FEMALE", "FEMALE"), ("OTHER", "OTHER")],
                max_length=10,
            ),
        ),
    ]
